//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCicek
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebCicekEntities : DbContext
    {
        public WebCicekEntities()
            : base("name=WebCicekEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AltKategoriler> AltKategoriler { get; set; }
        public DbSet<Fatura> Fatura { get; set; }
        public DbSet<GonderilecekYer> GonderilecekYer { get; set; }
        public DbSet<GonderimAmaci> GonderimAmaci { get; set; }
        public DbSet<Kategoriler> Kategoriler { get; set; }
        public DbSet<Kullanicilar> Kullanicilar { get; set; }
        public DbSet<SiparisDetay> SiparisDetay { get; set; }
        public DbSet<Siparisler> Siparisler { get; set; }
        public DbSet<Urunler> Urunler { get; set; }
    }
}
