//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCicek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int id { get; set; }
        public int siparisid { get; set; }
        public string faturabilgisi { get; set; }
        public string gönderenisim { get; set; }
        public string gönderentelefon { get; set; }
        public string gönderenadres { get; set; }
    
        public virtual Siparisler Siparisler { get; set; }
    }
}
