//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCicek
{
    using System;
    using System.Collections.Generic;
    
    public partial class GonderilecekYer
    {
        public GonderilecekYer()
        {
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int id { get; set; }
        public string konum { get; set; }
        public string aciklama { get; set; }
        public bool silindi { get; set; }
    
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
    }
}
