//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCicek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public Siparisler()
        {
            this.Fatura = new HashSet<Fatura>();
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int siparisid { get; set; }
        public int kullaniciID { get; set; }
        public string tarih { get; set; }
        public decimal tutar { get; set; }
        public string odemesekli { get; set; }
        public string siparisdurumu { get; set; }
    
        public virtual ICollection<Fatura> Fatura { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
    }
}
