//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCicek
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int id { get; set; }
        public int urunid { get; set; }
        public int siparisid { get; set; }
        public int gonderilecekid { get; set; }
        public int gamacid { get; set; }
        public string aliciad { get; set; }
        public string alicisoyad { get; set; }
        public string alicitelefon { get; set; }
        public string aliciadres { get; set; }
        public string kartmesaji { get; set; }
        public string kartisim { get; set; }
        public int adet { get; set; }
        public decimal fiyat { get; set; }
        public string birim { get; set; }
    
        public virtual GonderilecekYer GonderilecekYer { get; set; }
        public virtual GonderimAmaci GonderimAmaci { get; set; }
        public virtual Siparisler Siparisler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
