//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCicek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public Urunler()
        {
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int id { get; set; }
        public string urunkodu { get; set; }
        public string urunad { get; set; }
        public int altkategorino { get; set; }
        public int kategorino { get; set; }
        public int gonderimid { get; set; }
        public string aciklama { get; set; }
        public int adet { get; set; }
        public decimal fiyat { get; set; }
        public string birim { get; set; }
        public string resimyolu1 { get; set; }
        public string resimyolu2 { get; set; }
        public bool silindi { get; set; }
    
        public virtual AltKategoriler AltKategoriler { get; set; }
        public virtual GonderimAmaci GonderimAmaci { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
    }
}
